### ISSUE TITLE
ConversationStyle.creative is not creative

### ISSUE THREAD

**Issue by Eikosa** [Integration-Automation/ReEdgeGPT#101]
To observe this error try with the creative mode of copilot.microsoft.com and with the following code, the length and quality of the response is definitely not the same, the following code works more like balanced
```python
response = await bot.ask(
    prompt=prompt,
    conversation_style=ConversationStyle.creative,
    simplify_response=True,
    search_result = True
)
```

Example Prompt: `what is the sphygmomanometer?`

The answer given by the code:
> A sphygmomanometer is a device used to measure blood pressure. It has a cuff that wraps around the arm and a gauge that shows the pressure . You can buy different types of sphygmomanometers online. Do you want to know more about how to use it or why it is important?

Answer given by copilot.microsoft.com (expected behaviour)
>A sphygmomanometer is a device used to measure blood pressure. It consists of an inflatable cuff that is wrapped around the upper arm and a gauge that shows the pressure in the artery. The pressure is measured in millimeters of mercury (mmHg) and is recorded as two numbers: the systolic pressure (the pressure when the heart contracts) and the diastolic pressure (the pressure when the heart relaxes)
>The sphygmomanometer was invented in 1881 by Karl von Basch, an Austrian physician. He used an aneroid manometer, which is a dial that indicates the pressure by a needle. Later, mercury manometers were introduced, which use a column of mercury to show the pressure. Mercury manometers are considered the most accurate, but they are also hazardous and require careful handling
>There are also digital sphygmomanometers, which use electronic sensors and calculations to measure the pressure. They are easy to use and do not require a stethoscope, but they may be less accurate than manual ones. They may also be affected by certain conditions, such as arrhythmia, that alter the blood flow

**Comment by pixkk** [comment]
For author of ReEdgeGPT - Today i make some changes in code. 

At this moment i see, than next code:
```
"tone": "Precise"
```
works more better, than current:
```
"tone": conversation_style.name.capitalize()
```
As a test, try using for example the following query:

```“I’m asking you a question, answer with only one word and put !!! at the end of the sentence. Question - Is watermelon a melon?”```
(I don't know which different with first and second code (both are "Precise"))
