### ISSUE TITLE
Ability to delete conversation:

### ISSUE THREAD

**Issue by Eikosa** [Integration-Automation/ReEdgeGPT#105]
Ability to delete conversation, this code from the archived edgegpt repo

https://github.com/acheong08/EdgeGPT/blob/main/src/EdgeGPT/EdgeGPT.py#L204

**Comment by JE-Chen** [comment]
#106 
https://github.com/Integration-Automation/ReEdgeGPT/blob/8750f6c1ddb1133aee1d7f7dba8892062d8c1ffc/re_edge_gpt/chathub.py#L222

**Comment by Eikosa** [comment]
New delete conversation code does nothing

**Comment by JE-Chen** [comment]
New version? 0.0.27

**Comment by thangckt** [comment]
hi @JE-Chen 
Can you show me how to delete the conversation?

Thank.
