### ISSUE TITLE
 return images on creative style

### ISSUE THREAD

**Issue by FuseFairy** [Integration-Automation/ReEdgeGPT#109]
It's possible get images? Because right now only the text will be sent back first, maybe can wait until the images are done and then send them back together.

![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/78064680/a604d47e-f3b7-42b1-8df7-63abf5309243)

**Comment by JE-Chen** [comment]
如果你看他們的回傳會發現他們其實是用 Javascript 去做處理的，不是在同一個回覆中回覆產生的圖片
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/4dd84675-535b-43d3-b4f1-ad635c931eee)

**Comment by JE-Chen** [comment]
我有試過如果有圖片產生就保持 webscoket 連結，看起來是沒有效果:
type 1 是還在處理中
type 2 是處理完成
type 3 是回覆完成
type 6 是保持連結用的
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/b1dd947b-3356-48a8-a4da-fd6a3deb9241)

**Comment by JE-Chen** [comment]
簡單來說，不建議等圖片完成才發送，
Bing chat 在實作上也不是這樣做的，
他是先發送文字並取得第一次發送的回傳，
再用回傳來產生圖片，
我可以讓 response 包含應該要產生圖片的文字，
像是這樣:
```python
{
    "text": message["text"],
    "author": message["author"],
    "source_texts": source_texts,
    "source_links": source_links,
    "suggestions": suggestions,
    "image_create_text": "",
    "messages_left": messages_left,
    "max_messages": response["item"]["throttling"][
        "maxNumUserMessagesInConversation"
    ],
}
```

**Comment by JE-Chen** [comment]
```python
response = await bot.ask(
    prompt="Can u generate some food image",
    conversation_style=ConversationStyle.balanced,
    simplify_response=True,
    search_result=True
)
```

回傳大概是這樣

```python
{
  "text": "I'll try to create that. \n food",
  "author": "bot",
  "source_texts": [],
  "source_links": [],
  "suggestions": [
    "Can you draw a picture of pizza?",
    "How about drawing an image of sushi?",
    "Draw me some dessert"
  ],
  "image_create_text": "food",
  "messages_left": 29,
  "max_messages": 30
}
```

**Comment by FuseFairy** [comment]
got it, so there's no way to get this url? Because when you click on it, it's just a generated image.

![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/78064680/049ac476-5624-4cc2-935b-72f97ba8ba53)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/78064680/ec3ac4c5-7abf-4ac4-827e-1648e70a9117)

**Comment by JE-Chen** [comment]
You can self check image_create_text on next version 0.0.30 to simulate Bing chat's behavior like:
if image_create_text !="":
  # use image_create_text and ImageGen to generate image links
  # send image links to discord channel or what u want

**Comment by FuseFairy** [comment]
ok, thank you
