### ISSUE TITLE
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue

### ISSUE THREAD

**Issue by buithehien1991** [Integration-Automation/ReEdgeGPT#115]
When I run first time, it happen

```
 python3 bing.py                                                                                                       5s Py timdapan-data_platform Ruby 2.7.5 03:00:12 PM
Traceback (most recent call last):
  File "/Users/hienbt/Work/timdapan-data_platform/app/api/ai/bing.py", line 55, in <module>
    loop.run_until_complete(test_ask(image_url))
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/hienbt/Work/timdapan-data_platform/app/api/ai/bing.py", line 41, in test_ask
    raise error
  File "/Users/hienbt/Work/timdapan-data_platform/app/api/ai/bing.py", line 29, in test_ask
    response = await bot.ask(
               ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/re_edge_gpt/chat/re_edge_gpt.py", line 75, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/opt/homebrew/lib/python3.11/site-packages/re_edge_gpt/chat/chathub.py", line 179, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x107d433d0>
~/Work/timdapan-data_platform/app/api/ai master +3 !4 ?3 ❯                        
```

**Comment by JE-Chen** [comment]
Use newest cookie and use same account that you export cookie file to manual ask a question.

**Comment by JE-Chen** [comment]
And I don't know why, if you are using copilot mode this exception is usually than bing mode so much.

**Comment by FuseFairy** [comment]
> When I run first time, it happen
> 
> ```
>  python3 bing.py                                                                                                       5s Py timdapan-data_platform Ruby 2.7.5 03:00:12 PM
> Traceback (most recent call last):
>   File "/Users/hienbt/Work/timdapan-data_platform/app/api/ai/bing.py", line 55, in <module>
>     loop.run_until_complete(test_ask(image_url))
>   File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/Users/hienbt/Work/timdapan-data_platform/app/api/ai/bing.py", line 41, in test_ask
>     raise error
>   File "/Users/hienbt/Work/timdapan-data_platform/app/api/ai/bing.py", line 29, in test_ask
>     response = await bot.ask(
>                ^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/re_edge_gpt/chat/re_edge_gpt.py", line 75, in ask
>     async for final, response in self.chat_hub.ask_stream(
>   File "/opt/homebrew/lib/python3.11/site-packages/re_edge_gpt/chat/chathub.py", line 179, in ask_stream
>     raise Exception(
> Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x107d433d0>
> ~/Work/timdapan-data_platform/app/api/ai master +3 !4 ?3 ❯                        
> ```

just go to copilot.com, then send a random message and you'll know how to fix it.
