### ISSUE TITLE
ImageGenAsync.get_images lacking error output

### ISSUE THREAD

**Issue by Zaazu** [Integration-Automation/ReEdgeGPT#118]
As discussed in #116, `ImageGenAsync.get_images` should at least have similar error logging & handling as the non async version `ImageGen.get_images`.

While the non async function reports errors on prompts such as `error_being_reviewed_prompt`, `error_blocked_prompt` and `error_unsupported_lang`. The async function only has generic errors such as the prompt being blocked for unknown reasons.

**Comment by JE-Chen** [comment]
In the new version 0.0.34, `image_gen` will catch and raise an exception defined in `re_edge_gpt/utils/exception`. If no image is available, it will raise an `ImageCreateFailed` error. 
Is this enough?

**Comment by Zaazu** [comment]
Very nice, looking good!
