### ISSUE TITLE
Cookies expired and my account reached limit of the copilot usage in a day.

### ISSUE THREAD

**Issue by JayGarland** [Integration-Automation/ReEdgeGPT#128]
Another issue sir! sorry if I bothered you.
I opened creating conversations about 100 times if not 150 today.
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/128459480/ab686fac-ea60-42a2-8c4b-82495ddc117f)

**Comment by JE-Chen** [comment]
It’s Microsoft’s limit per day; there’s nothing I can do.

**Comment by JE-Chen** [comment]
You can use another Bing account’s cookie file to create a bot to avoid this. 
However, you still have a 300-message-per-day limit.

**Comment by JE-Chen** [comment]
We don’t have this feature at the moment.

**Comment by JE-Chen** [comment]
Can only run without cookies in some regions.
