### ISSUE TITLE
Copilot pro support

### ISSUE THREAD

**Issue by IKDH** [Integration-Automation/ReEdgeGPT#130]
With Copilot PRO, you can choose between gpt 4 or gpt 4 turbo in creative mode. Any chance to have this setup in the lib?

**Comment by JE-Chen** [comment]
I don’t have an Copilot Pro account for testing.

**Comment by IKDH** [comment]
Yes. For the Creative mode, GPT 4 Turbo is now used instead of GPT 4. If you want to use GPT 4, you need Copilot Pro.

**Comment by JE-Chen** [comment]
> Hello, here it is, now the creative and balanced are both using gpt4-turbo, while precise is still gpt4 <img alt="image" width="334" src="https://private-user-images.githubusercontent.com/128459480/315953086-572a0b54-638b-4786-9b8f-91c30d252ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTkxOTEsIm5iZiI6MTcxMTA5ODg5MSwicGF0aCI6Ii8xMjg0NTk0ODAvMzE1OTUzMDg2LTU3MmEwYjU0LTYzOGItNDc4Ni05YjhmLTkxYzMwZDI1MmJhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwOTE0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWEyM2VhYjM5YzFiNjhlYmI3OTZiNDg0OGFhYzcxNGNkZTQzZjJhZmJkZjBkMjM1YmMzNjI0YjAxNzg5NzE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jE7Jx8bLB6WtOttw3gp9_QPqsbrts2s5YX2kHOx5Xlk">

Do the Turbo or 4 switch buttons still exist?

**Comment by JE-Chen** [comment]
So maybe they want to replace GPT-4 with GPT-4 Turbo and they don’t want to provide a way to switch versions any more.

**Comment by IKDH** [comment]
No, you need to look at the web version :
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/30605776/f8b65b17-2681-4e70-a298-dd0d8958f25e)

I will send you the information

**Comment by IKDH** [comment]
Nothing is changing when I switch the toogle :
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/30605776/76fc0cbd-2fb6-44c5-8180-65305db16628)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/30605776/36d5e7ac-08cd-40da-ba76-93cebb076fc5)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/30605776/912fa2e1-7d6b-40f1-ad81-b5c59e344fa9)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/30605776/6858dbd1-f3cb-4790-8854-f8157ee3ad8a)

Maybe it's when you send a message that the change happened. I can do a Google Meet with you and share my screen if you want.

**Comment by IKDH** [comment]
Yes, I have subscribed to Copilot pro. Otherwise, you can't switch back to GPT-4 (the toogle doesn't appear).

**Comment by JE-Chen** [comment]
When you ask Bing Chat something,
 it will create a connection and a WebSocket (wss) connection to Chathub.
 What payload does it create, and what message does Chathub send?
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/73f7192f-3777-43ee-978e-ac9a864d5144)

**Comment by JE-Chen** [comment]
![Uploading image.png…]()

![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/c9fd91c0-6f09-4567-9d2a-e3f596b038d8)

**Comment by IKDH** [comment]
When I check the differences between the arguments, I can see that :

With GPT4-Turbo : "tone":"Creative"


With GPT 4 : "tone":"CreativeClassic"

Do you want me to send you the all argument by email ?

**Comment by JE-Chen** [comment]
> When I check the differences between the arguments, I can see that :
> 
> With GPT4-Turbo : "tone":"Creative"
> 
> With GPT 4 : "tone":"CreativeClassic"
> 
> Do you want me to send you the all argument by email ?

Sure, thanks

**Comment by IKDH** [comment]
Done!

**Comment by JE-Chen** [comment]
Can u access GPT4-Turbo on new version ?

**Comment by IKDH** [comment]
Yes. I have managed to switch the GPT 4 version on another library. I have just replaced Creative by CreativeClassic.

CreativeClassic = GPT 4
Creative = GPT4 Turbo
