### ISSUE TITLE
docker installation and web api endpoint

### ISSUE THREAD

**Issue by carefulcomputer** [Integration-Automation/ReEdgeGPT#134]
thank you for creating this ! Here is my wishlist

1) can  you please share instructions on how I can run it in docker.
2) please consider adding an api endpoint in docker to interact with the re-edge-gpt. That way I can integrate it with my other apps written in nodejs.
3) allow image/document upload

i can understand some of these items may either be in dev or not planned. just wanted to check if you would consider them.

**Comment by carefulcomputer** [comment]
I already see a dockerfile in the repo and some webpages, does this app already have some of the things I am requesting ?

**Comment by JE-Chen** [comment]
Yeah but Dockerfile and API docs only have basic chat mode (no options, plugins, etc.)

**Comment by carefulcomputer** [comment]
got it. i will be eagerly looking for the update. your project is the only one which doesn't require selenium for bing chat and is really fast.

**Comment by JE-Chen** [comment]
Dockerfile and API endpoint are done.

**Comment by JE-Chen** [comment]
doc in localhost:7935/docs (http://localhost:7935/docs/)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/d2dbe301-d6e4-4898-8851-44a3a972e613)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/b8082c5a-c76c-4be8-8988-732dad075a53)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/90dab300-e88f-4c08-a164-fffda8cdbe20)

**Comment by carefulcomputer** [comment]
Thank you!
