### ISSUE TITLE
I did everything according to the instructions, the bot does not work

### ISSUE THREAD

**Issue by Roboxkin** [Integration-Automation/ReEdgeGPT#138]
I did everything according to the instructions, the bot does not work
Or rather, he’s not in the channel
How to add a bot to a channel?
How to invite?

**Comment by JE-Chen** [comment]
Invite bot to channel?
If you want to implement a chatbot, you need to work on the front-end.

**Comment by Roboxkin** [comment]
Thank you very much for the answer!
I already realized that this would be a difficult task for me))
I hope there will be such an opportunity in the future
