### ISSUE TITLE
set_conversation() is not working properly

### ISSUE THREAD

**Issue by cryinghost** [Integration-Automation/ReEdgeGPT#142]
The problem is that i'm getting right data to set to continue conversation but it doesn't want to do, after every new request bot creates a new one. Is there any solution, or it's problem between Telegram API and ReEdge?

```
@tg_bot.message_handler(commands=['ask'])
async def ask(message):
    bingbot = None

    try:
        
        user_id = message.from_user.id

        if user_id not in user_dialogs:
            user_dialogs[user_id] = {}

        cookies: list[dict] = json.loads(open(str(Path.cwd() / "Desktop" / "bing-telegram-bot-main" / "cookies.json"), encoding="utf-8").read())
        bingbot = await Chatbot.create(cookies=cookies)

        user_dialogs[user_id].update(await bingbot.chat_hub.get_conversation())
        await bingbot.chat_hub.set_conversation(dialog_data=user_dialogs[user_id])
    
        prompt = message.text.replace("/ask", "")

        response = await bingbot.ask(
            prompt=prompt,
            conversation_style=ConversationStyle.precise,
            simplify_response=True,
            message_type = "chat"
        )

        response_message = response["text"]
        response_data = response["max_messages"]
        response_left = response["messages_left"]

        print(json.dumps(response, indent=2, ensure_ascii=False))
        print(user_dialogs[user_id])

        await tg_bot.reply_to(message, f"💬 {response_message}\n\n🟢 {response_data-response_left}/30")
    except Exception as e:
        await tg_bot.reply_to(message, f"❗️Error has been occured while processing your request. Error description: {e}")
```

**Comment by JE-Chen** [comment]
It looks like you initialize a new chatbot instance every time you receive an ‘ask’ command. 
And update your user_dialogs[user_id] use new chatbot instance conversation info.
You need check user_dialogs[user_id] have conversation info or not first.
This problem just some logic error not ReEdgeGPT or Telegram error.

**Comment by JE-Chen** [comment]
It looks like you initialize a new chatbot instance every time you receive an ‘ask’ command. 
And update your user_dialogs[user_id] use new chatbot instance conversation info.
You need check user_dialogs[user_id] have conversation info or not first.
This problem just some logic error not ReEdgeGPT or Telegram error.
