### ISSUE TITLE
Useragent Change Request

### ISSUE THREAD

**Issue by Niansuh** [Integration-Automation/ReEdgeGPT#164]
@JE-Chen Please Give me UserAgent to replace for my repo github.com/Niansuh/Bingo

**Comment by JE-Chen** [comment]
"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0"

**Comment by JE-Chen** [comment]
Well, you can find user-agents and x-ms-useragent in the developer tools (F12). 
If you want to find mobile or other device user-agents and x-ms-useragent, you can use the Chrome device option.

**Comment by JE-Chen** [comment]
Nah, you can find someone to get user-agents and x-ms-useragent, but not me.

**Comment by JE-Chen** [comment]
> i found user agent Mozilla/5.0 (Linux; Android 8.0.0; SM-G955U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36 Edg/127.0.0.0
> 
> do you know how to get x-ms-useragent please

on the cookie too, under user-agents.

**Comment by JE-Chen** [comment]
I’m focused on Copilot, so I don’t want to access other models. But thank you for the information.

**Comment by JE-Chen** [comment]
I think we are no longer discussing the issue, so I will close it. I prefer to provide backend functionality rather than a full web page, but I’ll ensure it works well
