### ISSUE TITLE
KeyError: 'conversationSignature' -- is the wss://sydney resource killed?

### ISSUE THREAD

**Issue by fractaldna22** [Integration-Automation/ReEdgeGPT#22]
```markdown
File "C:\Users\psych\AppData\Local\Programs\Python\Python311\Lib\site-packages\re_edge_gpt\re_edge_gpt.py", line 23, in __init__
    self.chat_hub: ChatHub = ChatHub(
                             ^^^^^^^^
  File "C:\Users\psych\AppData\Local\Programs\Python\Python311\Lib\site-packages\re_edge_gpt\chathub.py", line 47, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'
```

Get this on both EdgeGPT and ReEdgeGPT. my bot comradeGPT on discord which was the best bot is no longer working i have no idea what to do

**Comment by JE-Chen** [comment]
Look #17

**Comment by fractaldna22** [comment]
ooo thank youu.. i see the signature

**Comment by JE-Chen** [comment]
Can you use EdgeGPT now ?

**Comment by fractaldna22** [comment]
it worrrks

[image: image.png]

actually no..

[image: image.png]

i manually entered the conversation ID from the link you posted but it
doesnt work for chat.. but image creator did work for the first time since
dalle3 came out so thats a start.

**Comment by fractaldna22** [comment]
it worrrks

 
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/37323518/1010dff7-10b2-4a72-b068-709fc9b215a7)



actually no..
 
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/37323518/a7685345-2c7e-4105-a076-cffed8adf21f)


i manually entered the conversation ID from the link you posted but it
doesnt work for chat.. but image creator did work for the first time since
dalle3 came out so thats a start.


There's actually no conversationSignature on the link https://edgeservices.bing.com/edgesvc/turing/conversation/create
only
```js
{
    "conversationId": "<value>",
    "clientId": "<value>",
    "result": {
        "value": "Success",
        "message": null
    }
}
```

**Comment by fractaldna22** [comment]
i did get a bunch of past conversationSignatures on this but i have no idea how to use this https://www.bing.com/turing/conversation/chats

**Comment by JE-Chen** [comment]
Can't use old conversationSignatures, 
Every chat have specific conversationSignatures,
Sometime no conversationSignatures is microsoft server problem,
Sometime no conversationSignatures  it's mean microsoft block you (I don't know how long).

**Comment by JE-Chen** [comment]
Until this link https://edgeservices.bing.com/edgesvc/turing/conversation/create have conversationSignatures
And like this json then  you can use EdgeGPT
`
{
    "conversationSignatures": "<value>",
    "conversationId": "<value>",
    "clientId": "<value>",
    "result": {
        "value": "Success",
        "message": null
    }
}
`

**Comment by JE-Chen** [comment]
I will PR try to fix this wait me 0.5 ~ 2 hr

**Comment by JE-Chen** [comment]
@fractaldna22  Update your ReEdgeGPT  and make version is re_edge_gpt 0.0.7 then try again

**Comment by fractaldna22** [comment]
ok i will try that. I tried manually inputting the values of the last conversation on that page and it wasnt responding to chats, but it was responding to buttons..  

![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/37323518/bbea0401-b2c6-4c2a-833c-418992a3d283)
XD

I have the Windows 11 Copilot by the way and bing works everywhere else so i dont think microsoft blocked me but im going to update this and try again, thanks for helping. 

ill let you know shortly.

**Comment by fractaldna22** [comment]
chat now works!   but now image creator doesnt work. redirect fail, and also in chat..
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/37323518/0c232d35-94be-415d-876e-81a896d853cf)

**Comment by fractaldna22** [comment]
no rush. if this is all that works for now, im happy with just chat. Image creator just might be down again on the website, i havent checked yet.  Thanks again!

**Comment by JE-Chen** [comment]
I think it's bing's DALL-E3 problem
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/a56dbbdc-71bf-454e-9720-1b4ef17187d7)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/e1ad9582-6e92-408c-a630-75689eb80701)

**Comment by JE-Chen** [comment]
Sometime image will block by bing i don't why

**Comment by JE-Chen** [comment]
But only happend on async image generation, you can use thread and queue to process sync  image generation like async.
I need to check why asnyc will block request.

**Comment by 1nv4510n** [comment]
for me image gen works well, but when they released dalle 3 you have to wait for a long time

**Comment by fractaldna22** [comment]
in this case it ever makes the request. the images arent waiting on the
creation page

**Comment by fractaldna22** [comment]
but it did work right the first time yesterday while chat wasnt working 
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/37323518/0ad5b31c-d1af-4162-9a95-7bbb644f3abd)

in the past i know that when dalle 3 is slow, the images are still on the creations page. but now if it says this 

![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/37323518/8de26e0a-744c-4a44-9cb0-1f4002da66e2)


theres no new images on the creation page for these

**Comment by fractaldna22** [comment]
maybe it was just bad luck. ill try again manually directly in vscode today.

**Comment by JE-Chen** [comment]
Still can't generate image on same time, so if image still creating or cookie out of date, re_edge_gpt will return None
and print
```
Image create failed pls check cookie or old image still creating
```
