### ISSUE TITLE
Too often the token expires

### ISSUE THREAD

**Issue by Eikosa** [Integration-Automation/ReEdgeGPT#26]
`UnauthorizedRequest: Token issued by https://sydney.bing.com/sydney is invalid (IDX10223: Lifetime validation failed. The token is expired. ValidTo (UTC): '10/7/2023 4:16:22 PM', Current time (UTC): '10/7/2023 7:12:32 PM'.)`

**Comment by JE-Chen** [comment]
Bing block ur connect, not this package problem.

**Comment by JE-Chen** [comment]
Still get this problem?
Are you china user?
I think bing block all china connect, 
You can use proxy like this  issue
https://github.com/ikechan8370/chatgpt-plugin/issues/440

**Comment by Eikosa** [comment]
Yes, this problem has been happening for a while, probably not from the library as you say, but it happens very often. By the way I am not a Chinese user

**Comment by JE-Chen** [comment]
This package CI/CD (auto test) never raises this error.
https://github.com/juzeon/SydneyQt/issues/49
This issue also says that we need to use proxy on this error.

**Comment by Eikosa** [comment]
What would you suggest for a solution?
