### ISSUE TITLE
RuntimeError: This event loop is already running cause using jupyter as editor

### ISSUE THREAD

**Issue by Yukimagi** [Integration-Automation/ReEdgeGPT#30]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[10], line 25
     23 if __name__ == "__main__":
     24     loop = asyncio.get_event_loop()
---> 25     loop.run_until_complete(test_ask())

File ~\anaconda3\Lib\asyncio\base_events.py:629, in BaseEventLoop.run_until_complete(self, future)
    618 """Run until the Future is done.
    619 
    620 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    626 Return the Future's result, or raise its exception.
    627 """
    628 self._check_closed()
--> 629 self._check_running()
    631 new_task = not futures.isfuture(future)
    632 future = tasks.ensure_future(future, loop=self)

File ~\anaconda3\Lib\asyncio\base_events.py:588, in BaseEventLoop._check_running(self)
    586 def _check_running(self):
    587     if self.is_running():
--> 588         raise RuntimeError('This event loop is already running')
    589     if events._get_running_loop() is not None:
    590         raise RuntimeError(
    591             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running

**Comment by JE-Chen** [comment]
你可以給我完整的程式碼嗎?
只有少數片段我會難以識別出錯誤是在哪裡發生的。

**Comment by Yukimagi** [comment]
排版有點怪，我重傳看看
import asyncio
import json
from pathlib import Path

from re_edge_gpt import Chatbot
from re_edge_gpt import ConversationStyle


async def test_ask() -> None:
    cookies = json.loads(open(
        str(Path(str(Path.cwd()) + "/bing_cookies.json")), encoding="utf-8").read())
    bot = await Chatbot.create(cookies=cookies)
    response = await bot.ask(
        prompt="find me some information about the new ai released by meta.",
        conversation_style=ConversationStyle.balanced,
        simplify_response=True,
    )
    await bot.close()
    print(json.dumps(response, indent=2))
    assert response


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test_ask())

**Comment by Yukimagi** [comment]
排版有點怪我重傳，非常感謝您
`import asyncio
import json
from pathlib import Path

from re_edge_gpt import Chatbot
from re_edge_gpt import ConversationStyle


async def test_ask() -> None:
    cookies = json.loads(open(
        str(Path(str(Path.cwd()) + "/bing_cookies.json")), encoding="utf-8").read())
    bot = await Chatbot.create(cookies=cookies)
    response = await bot.ask(
        prompt="find me some information about the new ai released by meta.",
        conversation_style=ConversationStyle.balanced,
        simplify_response=True,
    )
    await bot.close()
    print(json.dumps(response, indent=2))
    assert response


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test_ask())`

**Comment by JE-Chen** [comment]
你把運行那段改成這樣呢?

```
if __name__ == "__main__":
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = asyncio.get_event_loop()
    loop.run_until_complete(test_ask())
```

**Comment by Yukimagi** [comment]
C:\Users\USER\anaconda3\Lib\re\__init__.py:258: RuntimeWarning: coroutine 'test_ask' was never awaited
  return pattern.translate(_special_chars_map)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

--------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[14], line 28
     26 except RuntimeError:
     27     loop = asyncio.get_event_loop()
---> 28 loop.run_until_complete(test_ask())

File ~\anaconda3\Lib\asyncio\base_events.py:629, in BaseEventLoop.run_until_complete(self, future)
    618 """Run until the Future is done.
    619 
    620 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    626 Return the Future's result, or raise its exception.
    627 """
    628 self._check_closed()
--> 629 self._check_running()
    631 new_task = not futures.isfuture(future)
    632 future = tasks.ensure_future(future, loop=self)

File ~\anaconda3\Lib\asyncio\base_events.py:588, in BaseEventLoop._check_running(self)
    586 def _check_running(self):
    587     if self.is_running():
--> 588         raise RuntimeError('This event loop is already running')
    589     if events._get_running_loop() is not None:
    590         raise RuntimeError(
    591             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running

**Comment by JE-Chen** [comment]
我裝 anaconda 看看，說不定是他的問題。

**Comment by Yukimagi** [comment]
了解，謝謝您，還是您可以跟我說您是用什麼跑的，或是環境?非常感謝您!

**Comment by JE-Chen** [comment]
Pycharm 2023.1.4
Python 3.9 ~ 3.11 都有測試
套件抓 requirements 裡的全部最新

**Comment by Yukimagi** [comment]
好的，謝謝您~

**Comment by JE-Chen** [comment]
我剛注意到 conad 好像不能抓到 package 或許你可以用 VSCode 跟 原生 Python pip　試試看。

**Comment by JE-Chen** [comment]
除了 Conda install 抓不到package外，我用 Anaconda3 python3.9 是可以跑得。

**Comment by JE-Chen** [comment]
如果你是採用 Jupyter 要注意他原本就有啟用 asyncio，你可能要額外 安裝 nest-asyncio 
並在開頭 nest_asyncio.apply()

**Comment by Yukimagi** [comment]
我是使用Jupiter

JeffreyChen ***@***.***>於 2023年10月23日 週一，下午5:20寫道：

**Comment by Yukimagi** [comment]
我再試試，有問題再問您，非常感謝您！

Yuki Lin ***@***.***>於 2023年10月23日 週一，下午5:23寫道：

**Comment by JE-Chen** [comment]
```
import asyncio
import json
from pathlib import Path

from nest_asyncio import apply

from re_edge_gpt import Chatbot
from re_edge_gpt import ConversationStyle


async def test_ask() -> None:
    cookies = json.loads(open(
        str(Path(str(Path.cwd()) + "/bing_cookies.json")), encoding="utf-8").read())
    bot = await Chatbot.create(cookies=cookies)
    response = await bot.ask(
        prompt="find me some information about the new ai released by meta.",
        conversation_style=ConversationStyle.balanced,
        simplify_response=True,
    )
    await bot.close()
    print(json.dumps(response, indent=2))
    assert response


if __name__ == "__main__":
    apply()
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = asyncio.get_event_loop()
    loop.run_until_complete(test_ask())

```
試試看這個使用 nest_asyncio 的

**Comment by Yukimagi** [comment]
OK,appreciate that.

JeffreyChen ***@***.***>於 2023年10月23日 週一，下午5:26寫道：

**Comment by Yukimagi** [comment]
可以了~非常感謝您!

**Comment by JE-Chen** [comment]
也謝謝你，之前沒注意到這個問題，之後會寫在 README 跟 文件給人參考如何解決。
