### ISSUE TITLE
“ModuleNotFoundError when importing edgegpt on Python 3.11.5 on Windows”

### ISSUE THREAD

**Issue by ZeaMays14142** [Integration-Automation/ReEdgeGPT#37]
Description:
I’m encountering a ModuleNotFoundError when trying to import the edgegpt module in Python 3.11.5, even though the package appears to be installed correctly. The exact command I ran was python edge2.py and the contents of the edge2.py was:

import edgegpt
print(edgegpt.__file__)

Steps to Reproduce
Install edgegpt with pip install edgegpt.
Run the script edge2.py with the following content:

import edgegpt
print(edgegpt.__file__)
The script fails with a ModuleNotFoundError.

Expected Behavior
The script should run without errors and print the path to the edgegpt module.

Actual Behavior
The script fails with the following error:

Traceback (most recent call last):
  File "script.py", line 1, in <module>
    import edgegpt
ModuleNotFoundError: No module named 'edgegpt'

Environment
Python version: 3.11.5 edgegpt version: 0.13.2 (as per pip show edgegpt) Operating System: Windows

Additional Information
The output of where python is C:\Users\miche\AppData\Local\Programs\Python\Python311\python.exe. The Python and Scripts directories are included in the system’s PATH as per C:\Users\miche\OneDrive\Desktop>echo %PATH% C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\dotnet;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\WireGuard;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Users\miche\AppData\Local\Microsoft\WindowsApps;C:\Users\miche\AppData\Local\Programs\Python\Python311;C:\Users\miche\AppData\Local\Programs\Python\Python311\Scripts;C:\Program Files\Git\bin;

The output of pip show edgegpt is as follows: Name: EdgeGPT Version: 0.13.2 Summary: Reverse engineered Edge Chat API Home-page: https://github.com/acheong08/EdgeGPT Author: Antonio Cheong Author-email: acheong@student.dalat.org License: The Unlicense Location: C:\Users\miche\AppData\Local\Programs\Python\Python311\Lib\site-packages Requires: aiohttp, BingImageCreator, certifi, httpx, prompt-toolkit, requests, rich, websockets Required-by:

I have tried uninstalling and reinstalling the edgegpt package. I have tried restarting their PC. I have confirmed that they have the necessary permissions to access the edgegpt module in the C:\Users\miche\AppData\Local\Programs\Python\Python311\Lib\site-packages directory.

**Comment by JE-Chen** [comment]
You should pip install re_edge_gpt and get bing_cookie then try this code snippet:
```python
import asyncio
import json
from pathlib import Path

from re_edge_gpt import Chatbot
from re_edge_gpt import ConversationStyle


# If you are using jupyter pls install this package
# from nest_asyncio import apply


async def test_ask() -> None:
    bot = None
    try:
        cookies = json.loads(open(
            str(Path(str(Path.cwd()) + "/bing_cookies.json")), encoding="utf-8").read())
        bot = await Chatbot.create(cookies=cookies)
        response = await bot.ask(
            prompt="How to boil the egg",
            conversation_style=ConversationStyle.balanced,
            simplify_response=True
        )
        # If you are using non ascii char you need set ensure_ascii=False
        print(json.dumps(response, indent=2, ensure_ascii=False))
        # Raw response
        # print(response)
        assert response
    except Exception as error:
        raise error
    finally:
        if bot is not None:
            await bot.close()


if __name__ == "__main__":
    # If you are using jupyter pls use nest_asyncio apply()
    # apply()
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = asyncio.get_event_loop()
    loop.run_until_complete(test_ask())
```
If you still have problem, Leave an message.

**Comment by ZeaMays14142** [comment]
oh, my bad, thank you.
