### ISSUE TITLE
Does `re_edge_gpt.ImageGenAsync` have a timeout setting?

### ISSUE THREAD

**Issue by WindowsSov8forUs** [Integration-Automation/ReEdgeGPT#42]
This is my code:
```python
# 生成图片
async def gen_image(prompt: str) -> Union[list[str], str]:
    '''生成图片

    参数:
        prompt (str): 图片生成参数

    返回:
        Union[list[str], str]: 生成的图片列表或错误信息
    '''
    try:
        image_gen = ImageGenAsync(auth_cookie=cls.cookies.image_gen)
        image_list = await image_gen.get_images(prompt)
        if image_list is not None:
            return image_list
        else:
            return '没有图片生成。'
    except Exception as exception:
        return f'{type(exception).__name__}: {exception}'
```
When I pass `🐱` as the value of `prompt` to the method `image_list = await image_gen.get_images(prompt)`, the method runs for a long time without getting any output or throwing any errors. If there is no timeout setting, I think there should be a parameter setting that throws a `TimeoutError` and terminates the method when the running time is too long; if there is a timeout setting, how can I set it?

**Comment by JE-Chen** [comment]
Try new version.

**Comment by JE-Chen** [comment]
Any update?

**Comment by JE-Chen** [comment]
Try install new version later
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/5fc8775a-8704-4a05-84b3-fc14ba7ff00f)

**Comment by JE-Chen** [comment]
Add proxy support on image gen .
#46

**Comment by WindowsSov8forUs** [comment]
> Add proxy support on image gen . #46

It's running successfully now. thx.
