### ISSUE TITLE
http.client_exceptions.ClientConnectorError: Cannot connect to host sydney.bing.com:443 ssl:<ssl.SSLContext object at 0x000002A5431C7BC0> [getaddrinfo failed]

### ISSUE THREAD

**Issue by IKDH** [Integration-Automation/ReEdgeGPT#50]
I get this error frequently : http.client_exceptions.ClientConnectorError: Cannot connect to host sydney.bing.com:443 ssl:<ssl.SSLContext object at 0x000002A5431C7BC0> [getaddrinfo failed]

**Comment by JE-Chen** [comment]
Something is blocking your connection to sydney.bing.com, like on a company’s own network.

**Comment by JE-Chen** [comment]
You can use proxy to avoid this exception.

**Comment by IKDH** [comment]
It's working fine now. Maybe the problem was on Microsoft side. Thank you.
