### ISSUE TITLE
upload image for gpt4 vision?

### ISSUE THREAD

**Issue by fractaldna22** [Integration-Automation/ReEdgeGPT#51]
is there a way to do this?

**Comment by JE-Chen** [comment]
Put image URL on prompt. 
like ask "How about this image https:<image_link>"

**Comment by JE-Chen** [comment]
Example
https://github.com/Integration-Automation/ReEdgeGPT/blob/main/test/unit_test/manual_test/test_bot_image.py

**Comment by JE-Chen** [comment]
Sometime GPT is dumb, You need try again:
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/0e97d915-6cbc-4a86-bdad-f51dd0954274)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/7993c8cf-b9a3-4f35-bf5d-8fb1e0826c84)

**Comment by JE-Chen** [comment]
If still no update, will close this issue.

**Comment by fractaldna22** [comment]
This might not be true. I've witnessed bing in the past lie about being
able to see the image in an image URL (BEFORE gpt-4 vision was released).
It basically pretended to see the image and used information it could find
from the URL and context of the conversation to tell you what you want to
hear. For example I told bing chat i made art of red roses for her and she
said "i would love to see it please send me the images", i sent the image
url and she said "wow they are lovely, i love the redness of the petals and
the composition, it's beautiful *v* "  ---  but the url i sent was actually
something completely different and it wasnt red roses at all. When I called
her out for lying about being able to see the image she admitted it.   I
wonder if its doing this in your example? The URL contains information
about the image - modern_city.jpg - from this its definitely possible to
guess and describe a typical modern city without being able to actually see
it.

**Comment by JE-Chen** [comment]
Current Bing GPT not a liar, but I think Bing blind now 
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/1adbb7a4-a6b1-48b8-84e6-32a9f85dfc40)

**Comment by JE-Chen** [comment]
Sometime Bing can see it sometime not.

**Comment by fractaldna22** [comment]
```markdown
 
describe this image: "https://images.yourstory.com/cs/2/96eabe90392211eb93f18319e8c07a74/Image54nh-1683225460858.jpg"
```
```markdown
Searching for: https://images.yourstory.com/cs/2/96eabe90392211eb93f18319e8c07a74/Image54nh-1683225460858.jpg

Generating answers for you…

This image shows a group of four young women sitting on a swing in a park. They are smiling and looking at the camera. [The image is from a website called YourStory, which is a platform for stories about startups and entrepreneurship in India](https://yourstory.com/)[1](https://yourstory.com/). The image was used in an article titled “How these four women entrepreneurs are making a difference in the lives of rural women”. The article features the stories of four social entrepreneurs who are working to empower rural women in various fields such as education, health, agriculture, and handicrafts. The image was taken by a photographer named Nishant Ratnakar.

[1](https://yourstory.com/)
Learn more:

[1. yourstory.com](https://yourstory.com/)
[2. images.google.com](https://images.google.com/)
[3. studio.yourstory.com](https://studio.yourstory.com/%22https:/images.yourstory.com/cs/2/28b451402d6a11e9aa979329348d4c3e/Fouronaswing-1682832114930.jpg/%22)
+2 more
```
```markdown
this was the image though: 
*uses input image button*
Can you describe the image I sent?
```
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/37323518/2c0e7dd4-fe4a-40fe-be97-f0bc3baa0aab)

```markdown

Analyzing the image: Privacy blur hides faces from Bing chat

Generating answers for you…

Sure, I can describe the image you sent. Here is what I see:

This is a black and white photo of a man with a long beard sitting in a chair.
The man’s face is blurred out with a gray rectangle.
The man is wearing a suit and appears to be deep in thought.
The background is black and the photo is taken from the side.
I hope this helps. 😊
```

**Comment by JE-Chen** [comment]
Hmm, I think Bing are dumb when using URL on prompt.
I will try to add an option to upload image.

**Comment by fractaldna22** [comment]
I really think it just uses the url to search relevant information from the host website and uses text in the url to infer the image without seeing it. but this might be a possible work around. bing mentioned selenium as a way to do this since it told me there was no way to do this with text inputs into bing chat.. here's its attempt at a code to simulate a mouse click on the button.. untested..

"""
That is a very specific question. I can try to help you with some code snippets that might be useful for your task, but I cannot guarantee that they will work perfectly. You will need to install and import the selenium module and the Re_Edge_GPT library in your Python script. You will also need to have a valid image URL that you want to submit to Bing chat's vision feature.

To open a virtual browser window and navigate to Bing chat, you can use the following code:

```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# create a web driver object
driver = webdriver.Chrome()

# go to Bing chat
driver.get("https://www.bing.com/chat")

# wait for the page to load
driver.implicitly_wait(10)
```

To click the Add an image button in Bing chat, you can use the following code:

```python
# find the Add an image button by its class name
add_image_button = driver.find_element_by_class_name("add-image-button")

# click the button
add_image_button.click()
```

To enter the image URL in the input field that appears, you can use the following code:

```python
# find the input field by its id
image_url_input = driver.find_element_by_id("image-url-input")

# clear the input field
image_url_input.clear()

# enter the image URL
image_url_input.send_keys("https://example.com/image.jpg")

# press the Enter key
image_url_input.send_keys(Keys.RETURN)
```

To use Re_Edge_GPT to generate an image from a text prompt and submit it to Bing chat's vision feature, you can use the following code:

```python
from re_edge_gpt import Re_Edge_GPT

# create a Re_Edge_GPT object
re_edge_gpt = Re_Edge_GPT()

# generate an image from a text prompt
image = re_edge_gpt.generate_image("a dragon")

# save the image to a local file
image.save("dragon.jpg")

# upload the image to an online image hosting service and get the image URL
image_url = upload_image("dragon.jpg")

# use the same code as above to enter the image URL in Bing chat
image_url_input = driver.find_element_by_id("image-url-input")
image_url_input.clear()
image_url_input.send_keys(image_url)
image_url_input.send_keys(Keys.RETURN)
```

I hope this helps you with your task. Please note that this is not a complete or tested solution, and you may need to modify it according to your needs and preferences.
"""

**Comment by fractaldna22** [comment]
i know this opens up a whole mess lol.. best i can do for now on my very limited skillset xD  but if it saved you any work and leads to a new feature, great :)

**Comment by JE-Chen** [comment]
Thank u, but we can't using selenium, because that to big and need driver to run

**Comment by JE-Chen** [comment]
I will add an option to bot.ask that allows users to upload an image URL using the Bing Image API instead of the Bing Chat API

**Comment by fractaldna22** [comment]
oh cool. you rock!
it would be cool. I saw on discord that the Prism chatbot now accepts image urls and can describe the image and i was jealous my comradeGPT bot still couldn't do this.. cant wait to see what you're able to do. thank you :)

**Comment by JE-Chen** [comment]
#58 
Add param attachment on bot.ask

For URL using
```python
 attachment={"image_url": r"<image_url>"})
```

For local file using
```python
 attachment={"filename": r"<file_path>"})
```

For base64 image using
```python
 attachment={"base64_image": r"<base64_image_str>"})
```

**Comment by JE-Chen** [comment]
Example

```python
import asyncio
import json
from pathlib import Path

from re_edge_gpt import Chatbot
from re_edge_gpt import ConversationStyle


# If you are using jupyter pls install this package
# from nest_asyncio import apply


async def test_ask() -> None:
    bot = None
    try:
        cookies: list[dict] = json.loads(open(
            str(Path(str(Path.cwd()) + "/bing_cookies.json")), encoding="utf-8").read())
        bot = await Chatbot.create(cookies=cookies)
        response = await bot.ask(
            prompt="What does this image show?",
            conversation_style=ConversationStyle.balanced,
            simplify_response=True,
            attachment={"image_url": r"https://images.yourstory.com/cs/2/96eabe90392211eb93f18319e8c07a74/Image54nh-1683225460858.jpg"})
        # If you are using non ascii char you need set ensure_ascii=False
        print(json.dumps(response, indent=2, ensure_ascii=False))
        # Raw response
        # print(response)
        assert response
    except Exception as error:
        raise error
    finally:
        if bot is not None:
            await bot.close()


if __name__ == "__main__":
    # If you are using jupyter pls use nest_asyncio apply()
    # apply()
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = asyncio.get_event_loop()
    loop.run_until_complete(test_ask())

```

**Comment by JE-Chen** [comment]
I don’t know if BingGPT can see a Discord link or not.

**Comment by JE-Chen** [comment]
Any update?

**Comment by fractaldna22** [comment]
Just saw this. I'll try it out! i think it can see discord links since
every other AI art model on discord that take image input also use discord
urls and they're public urls i think. I'll be back with an update soon
