### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PushkarOP** [Integration-Automation/ReEdgeGPT#59]
Nov 27 09:39:11 AM  ERROR: Could not find a version that satisfies the requirement re_edge_gpt (from -r requirements.txt (line 5)) (from versions: none)
Nov 27 09:39:11 AM  ERROR: No matching distribution found for re_edge_gpt (from -r requirements.txt (line 5))

**Comment by JE-Chen** [comment]
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/3a7dd61b-ea3d-4d7f-a30c-6a97719145e9)
Well I can install it.
Try use
```
 pip install re-edge-gpt
```

**Comment by JE-Chen** [comment]
pip install -r --upgrade is success too.
What env you are using for this.
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/841ce4e2-f4cd-4000-8368-0a8e5afd2779)

**Comment by PushkarOP** [comment]
fixed the issue, thx
