### ISSUE TITLE
Simplify response has redundant attributes.

### ISSUE THREAD

**Issue by sastpg** [Integration-Automation/ReEdgeGPT#65]
1. sources and adaptive_texts are totally same:
```
adaptive_text = (
    adaptive_cards[0]["body"][0].get("text") if adaptive_cards else None
)
sources = (
    adaptive_cards[0]["body"][0].get("text") if adaptive_cards else None
)
```
2. sources and sources_text are hard to used since they mix the web search result and reply together.
I think a pure sourceAttributions would be more suitable for sources. My modification:
```
sources = [
    "[" + source["providerDisplayName"] + "](" + source["seeMoreUrl"] + ")"
    for source in message.get('sourceAttributions', [])
]
```

**Comment by JE-Chen** [comment]
1. It will be fixed.
2. That is Bing’s reply source. The original reply is mixed.
