### ISSUE TITLE
How to deal with this situation?

### ISSUE THREAD

**Issue by xiewenqian** [Integration-Automation/ReEdgeGPT#85]
AI ends the current conversation after replying to the following sentence. Useful content is in the next reply.
“好的，我会按照你的要求来做。请稍等一下。” (OK, I will do as you ask. please wait for a moment.)

**Comment by JE-Chen** [comment]
What you ask Bing.

**Comment by xiewenqian** [comment]
I asked Bing to rate the quality of a piece of text

**Comment by xiewenqian** [comment]
The content of this text exceeds 800 words

**Comment by JE-Chen** [comment]
Rate the quality of a piece of text on English:
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/74f564d1-54c7-41ac-8b25-d28253ffec1f)

Translate to Simplified Chinese:
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/62f3d0be-227b-44b6-89e2-23e206c524c4)

Rate the quality of a piece of text on Simplified Chinese:
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/38664d57-2167-420e-ac4f-7b57704cad6f)

I cannot reproduce the error. Maybe you have reached the chat limit? If you have reached the limit, Bing will automatically create a new conversation. If you use the same cookie for a long time, the maximum number of messages is limited to 10.

![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/faf032cd-51b6-4e65-9d00-fa1441b81f17)

**Comment by xiewenqian** [comment]
Thank you for your answer. This problem does not appear every time. It seems like some kind of friendly prompt that appears when AI is dealing with a more complex problem.

**Comment by JE-Chen** [comment]
```
# Before ask
conversation_dict = {}
conversation_dict.update(await bot.chat_hub.get_conversation())
# After ask
await bot.chat_hub.set_conversation(conversation_dict=conversation_dict)
```
