### ISSUE TITLE
Authentication failed on linux

### ISSUE THREAD

**Issue by itskekoff** [Integration-Automation/ReEdgeGPT#86]
Recently started using this, works perfectly but after some time - Authentication failed.
On windows all works.

**Comment by JE-Chen** [comment]
Have you renew server cookie file and use proxy

**Comment by itskekoff** [comment]
yes

пн, 8 янв. 2024 г., 15:33 JeffreyChen ***@***.***>:

**Comment by JE-Chen** [comment]
Can you try another proxy service or no proxy?

**Comment by JE-Chen** [comment]
And try to manual ask bing a problem, maybe have some CaptchaChallenge.

**Comment by itskekoff** [comment]
> Can you try another proxy service or no proxy?

no proxy - im from russia. tested on pc using wireguard - all works, on linux - not found page instead of json data

**Comment by JE-Chen** [comment]
Still work on my ubuntu server, vm, docker

**Comment by JE-Chen** [comment]
Try new version that using copliot.com not bing.com

**Comment by JE-Chen** [comment]
And pls renew your cookie using copliot.com not bing.com

**Comment by itskekoff** [comment]
idk what happened but it fixed.

**Comment by JE-Chen** [comment]
hmm maybe it's proxy service provider problem?
