### ISSUE TITLE
failed to create Chatbot, KeyError: 'X-Sydney-Conversationsignature' 

### ISSUE THREAD

**Issue by SXK485** [Integration-Automation/ReEdgeGPT#89]
The response header for the request to 

> https://copilot.microsoft.com/turing/conversation/chats

 is as follows: 
`Headers([('cache-control', 'private'), ('content-length', '4929'), ('content-type', 'application/json; charset=utf-8'), ('content-encoding', 'gzip'), ('vary', 'Accept-Encoding'), ('p3p', 'CP="NON UNI COM NAV STA LOC CURa DEVa PSAa PSDa OUR IND"'), ('set-cookie', 'MUIDB=18B68917F1F06D500E6D9D13F01E6C55; expires=Wed, 05-Feb-2025 07:45:19 GMT; path=/; HttpOnly'), ('set-cookie', 'SRCHHPGUSR=SRCHLANG=en&PV=15.0.0&BRW=N&BRH=S&CW=1253&CH=660&SCW=1238&SCH=660&DPR=1.0&UTC=480&DM=0&CIBV=1.1418.9-suno&PRVCW=1253&PRVCH=660; expires=Wed, 05-Feb-2025 07:45:19 GMT; path=/; secure; SameSite=None'), ('access-control-allow-credentials', 'true'), ('access-control-allow-headers', 'x-ms-client-request-id, x-ms-useragent'), ('access-control-allow-methods', 'GET'), ('access-control-allow-origin', 'https://www.bing.com'), ('x-eventid', '65a0ee0ff37a427e8655c324202cd33e'), ('accept-ch', 'Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA'), ('useragentreductionoptout', 'A7kgTC5xdZ2WIVGZEfb1hUoNuvjzOZX3VIV/BA6C18kQOOF50Q0D3oWoAm49k3BQImkujKILc7JmPysWk3CSjwUAAACMeyJvcmlnaW4iOiJodHRwczovL3d3dy5iaW5nLmNvbTo0NDMiLCJmZWF0dXJlIjoiU2VuZEZ1bGxVc2VyQWdlbnRBZnRlclJlZHVjdGlvbiIsImV4cGlyeSI6MTY4NDg4NjM5OSwiaXNTdWJkb21haW4iOnRydWUsImlzVGhpcmRQYXJ0eSI6dHJ1ZX0='), ('content-security-policy-report-only', "script-src https: 'strict-dynamic' 'report-sample' 'nonce-R639invmWTbRIPvlgtNu5/VrehQrPkcCuQIsVzEYDf0='; base-uri 'self';report-to csp-endpoint"), ('report-to', '{"group":"csp-endpoint","max_age":86400,"endpoints":[{"url":"https://aefd.nelreports.net/api/report?cat=bingcsp"}]}'), ('x-ceto-ref', '65a0ee0ff37a427e8655c324202cd33e|2024-01-12T07:45:19.216Z'), ('x-cache', 'CONFIG_NOCACHE'), ('x-msedge-ref', 'Ref A: CD12C50EFE1A489095D2769DD2593B50 Ref B: LTSEDGE1414 Ref C: 2024-01-12T07:45:19Z'), ('date', 'Fri, 12 Jan 2024 07:45:18 GMT')])`
——The `X-Sydney-Conversationsignature` and `X-Sydney-Encryptedconversationsignature` fields are missing. 

When I replace 

> https://copilot.microsoft.com/turing/conversation/chats

 with 

> https://copilot.microsoft.com/turing/conversation/create

, I can create a Chatbot normally.

**Comment by JE-Chen** [comment]
Sorry for reply later, this should be fix on new version.

**Comment by JE-Chen** [comment]
Try new version 0.0.22

**Comment by SXK485** [comment]
> Try new version 0.0.22

Thank you for the fix, the new version is working now.

**Comment by FuseFairy** [comment]
Only get ver0.0.23, so I update to 0.0.23, but still get the `KeyError: 'X-Sydney-Conversationsignature'`
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/78064680/65fff184-4ba5-4835-b2f8-f64a598e5749)
