### ISSUE TITLE
end point is not latest

### ISSUE THREAD

**Issue by FuseFairy** [Integration-Automation/ReEdgeGPT#91]
Does it work with the latest endpoints? Because there is a gap between the current and the web version of the answer.

**Comment by JE-Chen** [comment]
Checking

**Comment by JE-Chen** [comment]
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/edee4c25-49ca-426c-878f-d5cb2c7abaec)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/0f07c0d1-d11b-4fba-a691-ecccf4b414d1)

### Idk why, but even constant is newest Bing reply same answer 

![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/817ce73f-e138-4b21-83b6-898babf7f855)
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/84c0cb17-51c1-4f9f-b03c-82c6df898ad3)

**Comment by FuseFairy** [comment]
So strange, and I can get same response from this repo, maybe you could look into it.
https://github.com/vsakkas/sydney.py

**Comment by JE-Chen** [comment]
If have more word Bing will generate diff response, I still dk why

**Comment by JE-Chen** [comment]
Look like it's AI model's problem, everything on code is newest.

**Comment by pixkk** [comment]
i have same problem.

In web page answers better, than in re-edge-gpt.

**Comment by JE-Chen** [comment]
U can see what version of Bing current using when  simplify_response=False
```python
        response = await bot.ask(
            prompt="Beef wellington recipe",
            conversation_style=ConversationStyle.balanced,
            simplify_response=False
        )
```
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/9fdb2bff-21dc-4fb1-9281-3c7d23c526ec)

And u can use search_result=True to make answer better (maybe)
```python
        response = await bot.ask(
            prompt="Beef wellington recipe",
            conversation_style=ConversationStyle.balanced,
            simplify_response=True,
            search_result=True
        )
```

**Comment by pixkk** [comment]
I just wanted to clarify what “simplify_response” means, since I couldn’t find any explanation in the documentation. Does it just display in convenient json?

Okay, I'll try to see the results.

**Comment by JE-Chen** [comment]
> I just wanted to clarify what “simplify_response” means, since I couldn’t find any explanation in the documentation. Does it just display in convenient json?
> 
> Okay, I'll try to see the results.

* Yes simplify_response just display in convenient json.

**Comment by pixkk** [comment]
i`m tested my prompts. I'm guessing it gives "Balanced" style responses regardless of the fact that I specified conversation_style=ConversationStyle.precise.

**Comment by pixkk** [comment]
@JE-Chen 
Maybe i found problem - in file https://github.com/Integration-Automation/ReEdgeGPT/blob/main/re_edge_gpt/request.py

```python
self.struct = {
            "arguments": [
                {
                    "source": "cib",
                    "optionsSets": [

```

If i change optionsSets to actual precise, it works fine (answers from browser and re-edge-gpt are same):
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/30828435/8fcab027-b9b1-4d55-bb67-e6ca57828013)

**Comment by JE-Chen** [comment]
Thx, do u wan to open PR fix this problem?
