### ISSUE TITLE
KeyError: 'X-Sydney-Conversationsignature'

### ISSUE THREAD

**Issue by FuseFairy** [Integration-Automation/ReEdgeGPT#93]
Only get ver0.0.23, so I update to 0.0.23, but still get the `KeyError: 'X-Sydney-Conversationsignature'`
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/78064680/65fff184-4ba5-4835-b2f8-f64a598e5749)

**Comment by JE-Chen** [comment]
Fixing, idk why GitHub Actions is still success

**Comment by JE-Chen** [comment]
Release ver 0.0.24

**Comment by FuseFairy** [comment]
can working now, thank you!
